from __future__ import annotations

from shared.env_config import env_flag, env_int

BROWSER_AUTH_HEADLESS = env_flag("BROWSER_AUTH_HEADLESS", True)
FBA_LOGISTICS_TOKEN_HEADLESS = env_flag("FBA_LOGISTICS_TOKEN_HEADLESS", BROWSER_AUTH_HEADLESS)
BROWSER_AUTH_LOCK_TIMEOUT_SECONDS = env_int("BROWSER_AUTH_LOCK_TIMEOUT_SECONDS", 180, minimum=1)
BROWSER_AUTH_FORCE_COOLDOWN_SECONDS = env_int("BROWSER_AUTH_FORCE_COOLDOWN_SECONDS", 30, minimum=0)


__all__ = [
    "BROWSER_AUTH_HEADLESS",
    "BROWSER_AUTH_FORCE_COOLDOWN_SECONDS",
    "BROWSER_AUTH_LOCK_TIMEOUT_SECONDS",
    "FBA_LOGISTICS_TOKEN_HEADLESS",
]
