from __future__ import annotations

from shared.env_config import env_flag, env_int, env_text


LOGISTICS_USE_REMOTE_API = env_flag("LOGISTICS_USE_REMOTE_API", True)
LOGISTICS_REMOTE_API_BASE_URL = env_text("LOGISTICS_REMOTE_API_BASE_URL", "")
LOGISTICS_LOCAL_API_BASE_URL = env_text("LOGISTICS_LOCAL_API_BASE_URL", "http://127.0.0.1:8000")
LOGISTICS_API_BASE_URL = (
    LOGISTICS_REMOTE_API_BASE_URL if LOGISTICS_USE_REMOTE_API else LOGISTICS_LOCAL_API_BASE_URL
)
LOGISTICS_API_TIMEOUT_SECONDS = env_int("LOGISTICS_API_TIMEOUT_SECONDS", 30, minimum=1)
LOGISTICS_IMPORT_POLL_INTERVAL_SECONDS = env_int("LOGISTICS_IMPORT_POLL_INTERVAL_SECONDS", 10, minimum=0)
LOGISTICS_IMPORT_MAX_POLLS = env_int("LOGISTICS_IMPORT_MAX_POLLS", 6, minimum=0)


__all__ = [
    "LOGISTICS_API_BASE_URL",
    "LOGISTICS_API_TIMEOUT_SECONDS",
    "LOGISTICS_IMPORT_MAX_POLLS",
    "LOGISTICS_IMPORT_POLL_INTERVAL_SECONDS",
    "LOGISTICS_LOCAL_API_BASE_URL",
    "LOGISTICS_REMOTE_API_BASE_URL",
    "LOGISTICS_USE_REMOTE_API",
]
